Fixed. NoMethodError when photo is not found
```
NoMethodError: private method `select' called for nil:NilClass
./lib/cure_line/post.rb:44:in `photo_urls'
./spec/cure_line/post_spec.rb:74:in `block (3 levels) in <top (required)>'
./spec/cure_line/post_spec.rb:82:in `block (4 levels) in <top (required)>'
```